version: '3'
services:
  node-app:
    build: .
    # container_name: mycont
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  mongo:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
        - mongo-db:/data/db
volumes:
  mongo-db: