version: '3'
services:
  node-app:
    build: 
      context: .
      args:
      - NODE_ENV=development  # Correct way to pass build arguments
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
    volumes:
      - ./:/app  # Correct the volume mount path
      - /app/node_modules  # Anonymous volume to avoid overriding node_modules
    command: npm run dev
